config/routes.rb
Rails.application.routes.draw do
   devise_for :users
  root 'books#top'
  get 'home/about' => 'books#about'
  get 'search' => 'searches#search'
  resources :users, only: [:index, :edit, :update, :show] do
    resources :relationships, only: [:create, :destroy]
    resources :parents
    get 'relationships/create'
    get 'relationships/destroy'
  end
 
  resources :books, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy] 
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :book_comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
 before_action :authenticate_user!

  def create
   	book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
  	@book_comment.book_id = book.id
    @book_comments = BookComment.all
  	@book_comment.save
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:book_comment, :user_id, :book_id)
  end
  def correct_user
    @book_comment = BookComment.find(params[:id])
    if current_user != @book_comment.user
    end
  end
end  

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
      <!-- コメント表示　-->
<% @book_comments.each do |book_comment| %>
 <table class="table">
  <thead>
    <tr>
      <th>
      <div class="comment-body bb">
        <div class="comment-avatar">
          <div class="avatar">
            <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%><br><br><br>
          </div>
        </div>
        <div class="comment-text">
          <div class="comment-author clearfix">
            <%= book_comment.user.name %>
            <span class="comment-meta">
            </span>
          </div>
        </th>
        <th>
          <div class="comment-entry"><%= book_comment.book_comment %></div>
          </th>
          <th>
            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
             <% end %>
            </div>
          </th>

           <% end %>
            </div>
          </div>
        </thead>
      </table>
  

app/views/book_comments/_comment_form.html.erb
<%= form_with(model: [@book,@book_comment], url: book_book_comments_path(@book) ) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :comment_content, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
    </div>
  </div>
<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/book_comments/create.js.erb
$('#comment-create').html("<%= j(render partial: 'book_comments/comment', locals: { book_comment: @book_comments }) %>");
$('textarea').val('')

app/views/book_comments/destroy.js.erb
$('#comment-create').html("<%= j(render partial: 'book_comments/comment', locals: { book_comment: @book_comments }) %>");
$('textarea').val('')