config/routes.rb
Rails.application.routes.draw do
   devise_for :users
  root 'books#top'
  get 'home/about' => 'books#about'
  get 'search' => 'searches#search'
  resources :users, only: [:index, :edit, :update, :show] do
    resources :relationships, only: [:create, :destroy]
    resources :parents
    get 'relationships/create'
    get 'relationships/destroy'
  end
 
  resources :books, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy] 
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :profile_image, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image
  
  has_many :active_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower # 自分がフォローしている人
  has_many :passive_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :followed # 自分をフォローしている人
  
  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(followed_id: user.id).present?
  end
  
  validates :name, presence: :true,
                   length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end
  
  def self.search(search,word)
    if search == "forward_match"
    @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
    @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
    @user = User.where("#{word}")
    elsif search == "partial_match"
    @user = User.where("name LIKE?","%#{word}%")
    else
    @user = User.all
  end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!

  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
  end

  def show
    @book_new = Book.new
    @users = User.all
    @user = User.find(params[:id])
    @books = @user.books.all
   #imageを渡す記述
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
   else
     flash[:danger] = @user.errors.full_messages
     render "edit"
   end
  end
  
  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<h1>User info</h1>
<%= attachment_image_tag(user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg") %><br>
 <table class="table">
  <thead>
	  <tr>
	  <th>name</th><th><%= user.name %></th></tr>
	  <tr>
	  <th>introduction</th><th><%= user.introduction %></th></tr>
	  <tr>
	    <th>follows</th><th><%= link_to "#{user.active_relationships.count} ", follows_user_path(user.id) %></tr>
	    <th>followers</th><th><%= link_to "#{user.passive_relationships.count} ", followers_user_path(user.id) %></th>
	  </tr>
  </thead>
 </table>
 <%= link_to "",edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<%= @user.errors.count %>errors
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
  </div>

   <div class="form-group">
      <%= f.label :image %><br />
      <%= f.attachment_field :profile_image,class: "user_image" %>
    </div>

    <div class="form-group">
      <%= f.label :introduction %><br />
      <%= f.text_area :introduction,class: "form-control introduction"%>
    </div>


    <div class="actions">
    <%= f.submit "Update User", class: "btn btn-primary" %>
    </div>

<% end %>

app/views/users/followers.html.erb
<div class="container">
  <h2>Follower Users</h2>
  <% @users.each do |user| %>
  <table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th><%= attachment_image_tag user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%></th>
			<td><%= user.name %></td>
			<td><%= "フォロー数：#{@user.active_relationships.count} " %></td>
			<td><%= "フォロワー数：#{@user.passive_relationships.count} " %></td>
			<td><%= link_to "Show",user_path(user) %></td>
		</tr>
		
	</tbody>
</table>
    
  <% end %>

</div>

app/views/users/follows.html.erb
<div class="container">
  <h2>Follow Users</h2>
  <% @users.each do |user| %>
  <table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th><%= attachment_image_tag user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%></th>
			<td><%= user.name %></td>
			<td><%= "フォロー数：#{@user.active_relationships.count} " %></td>
			<td><%= "フォロワー数：#{@user.passive_relationships.count} " %></td>
			<td><%= link_to "Show",user_path(user) %></td>
		</tr>
		
	</tbody>
</table>
    
  <% end %>

</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
<%= render 'users/profile', user: current_user %>

    	<h1>New book</h1>
<%= render 'layouts/error.message'  %>
<% @book.errors.full_messages.each do |message| %>
 <% end %>

<%= form_with model: @book,  local:true do |f| %>
<!-- form_with model: @book, url:'/books', local:true do |f|  -->
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
   <%= f.submit "Create Book", class: "btn btn-primary" %>

<% end %>
</div>


<div class="col-xs-9">
<table class="table table-striped">

<h1>Users</h1>


    <table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>

		</tr>
	</thead>
	<% @users.each do |user| %>
	<tbody>

		<tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%></td>
      <td style="border:none;"><%= user.name %></td>
      <td>
      <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
          <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
        <% else %>
        <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
        <% end %>
      <% end %>
      </td>
		  <td><%= link_to "Show",user_path(user) %></td>
		 </tr>

    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class="container">  <!-- この行を追加 -->
 <div class="row">
  <div class="col-xs-3">
  <h1>User info</h1>
<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%><br>
 <table class="table">
  <thead>
	  <tr>
	  <th>name</th><th><%= @user.name %></th></tr>
	  <tr>
	  <th>introduction</th><th><%= @user.introduction %></th></tr>
	   <tr>
	    <th>follows</th><th><%= link_to "#{@user.active_relationships.count} ", follows_user_path %></tr>
	    <th>followers</th><th><%= link_to "#{@user.passive_relationships.count} ", followers_user_path %></th>
	  </tr>
  </thead>
 </table>
  
    <% if current_user.id != @user.id %>
        <% if @user.followed_by?(current_user) %>
          <%= link_to 'フォロー外す', user_relationships_path(@user.id), class: "btn btn-primary",  method: :delete %>
        <% else %>
        <%= link_to 'フォローする', user_relationships_path(@user.id), class: "btn btn-primary", method: :post %>
        <% end %>
        <% else %>
        <%= link_to "",edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
      <% end %>
  
  
   <h1>New book</h1>
   <%= form_with model: @book_new,  local:true do |f| %>
   <h4>Title</h4>
   <%= f.text_field :title %>
   <h4>Opinion</h4>
   <%= f.text_area :body %>
   <%= f.submit "Create Book", class: "btn btn-primary" %>
 <% end %>
  </div>
  <div class="col-xs-9">
    <table class="table table-striped">
    <h2>Books</h2>
    <table class='table'>
      <thead>
       <tr>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
       </tr>
      </thead>
      <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><span><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></span></td>
          <td><span><%= link_to book.title,book_path(book)%></span></td>
          <td><span><%= book.body %></span></td>
          
         
          
          <td>
          <ul class="inline-meta">
              <%= link_to "コメント数： #{book.book_comments.count} ", book_path(book.id) %>
          </ul>
        </td>
        </tr>
      <% end %>
      </tbody>
    </table>