config/routes.rb
Rails.application.routes.draw do
   devise_for :users
  root 'books#top'
  get 'home/about' => 'books#about'
  get 'search' => 'searches#search'
  resources :users, only: [:index, :edit, :update, :show] do
    resources :relationships, only: [:create, :destroy]
    resources :parents
    get 'relationships/create'
    get 'relationships/destroy'
  end
 
  resources :books, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy] 
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }
  def self.search(search, word)
        if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @book = Book.where("#{word}")
        elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
        else
                        @book = Book.all
        end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = BookComment.all
    @users = User.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if  @book.save
     flash[:notice] = "book was successfully created."
     redirect_to book_path(@book)
    else
      @books = Book.all
      render :"index"
    end
  end

  def edit
   @book = Book.find(params[:id])
   @user = @book.user
   if @user != current_user
     redirect_to books_path
   end
  end

  def update
    @book = Book.find(params[:id])
    book = Book.find(params[:id])
    if book.update(book_params)
     flash[:notice] = "You have updated book successfully."
     redirect_to book_path
    else
      flash[:danger] = "error!"
      render :"edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Deleted successfully"
    redirect_to '/books'
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_header.html.erb
<% @books.each do |books| %>

<header>
  <div class="title">Bookers</div>
  <span class="glyphicon glyphicon-home" aria-hidden="true">Home</span>
  
</header>
<% end %>
<%= paginate books %>

app/views/books/about.html.erb
<main>
<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>
</main>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= flash[:danger] %>
<%= form_with model:@book, local: true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Update Book', class: "btn btn-primary" %>
<% end %>

 <%= link_to "Show", book_path(@book) %>
 <%= link_to "Back", books_path %>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<%= render 'layouts/error.message'  %>
  <% @book.errors.full_messages.each do |message| %>
<% end %>
<div class="container">  <!-- この行を追加 -->
　<div class="row">
　　<div class="col-xs-3">
　<%= render 'users/profile', user: current_user %>
      <h1>New book</h1>
      <%= form_with model: @book,  local:true do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
       <%= f.text_area :body %>
        <%= f.submit "Create Book", class: "btn btn-primary" %>
       <% end %>
    </div>
    <div class="col-xs-9">
      <table class="table table-striped">
        <h1>Books</h1>
      <thead>
		<tr>
		<th></th>
	    <th>Title</th>
		<th>Opinion</th>
		</tr>
	  </thead>
	<% @books.each do |book| %>
	  <tbody>
		<tr>
		  <td>
		    <%= link_to user_path(book.user) do %>
		    <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
		    <% end %></td>
		  <td><%= link_to book.title, book_path(book) %></td>
      <td><%= book.body %></td>
      <!-- いいね　-->
      <td class="favorites_buttons_<%= book.id %>">
        <%= render 'favorites/favorite-btn', book:book %>
      </td>
         
        <td>
          <ul class="inline-meta">
              <%= link_to "コメント数： #{book.book_comments.count} ", book_path(book.id) %>
          </ul>
        </td>
		  </tr>
    <% end %>
       </tbody>
       </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class="container">  <!-- この行を追加 -->
  <div class="row">
    <div class="col-xs-3">
  <h1>User info</h1>
<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%><br>
 <table class="table">
  <thead>
	  <tr>
	  <th>name</th><th><%= @user.name %></th></tr>
	  <tr>
	  <th>introduction</th><th><%= @user.introduction %></th></tr>
	   <tr>
	    <th>follows</th><th><%= link_to "#{@user.active_relationships.count} ", follows_user_path %></tr>
	    <th>followers</th><th><%= link_to "#{@user.passive_relationships.count} ", followers_user_path %></th>
	  </tr>
  </thead>
 </table>
  
    <% if current_user != @user %>
      <% if @user.followed_by?(current_user) %>
        <%= link_to 'フォロー外す', user_relationships_path(@user.id), class: "btn btn-primary",  method: :delete %>
      <% else %>
        <%= link_to 'フォローする', user_relationships_path(@user.id), class: "btn btn-primary", method: :post %>
      <% end %>
    <% else %>
    <%= link_to "",edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
    <% end %>
  
 
 
      <h1>New book</h1>
      <%= render 'layouts/error.message'  %>
      <%= form_with model: @book_new,  local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
　     　<%= f.submit "Create Book", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-xs-9">
      <h1>Book detail</h1>
      <table class="table table-striped">
	      <tbody>
	        <tr>
            <td style="border:none;"><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
            <br><br><br><%= link_to @user.name, user_path(@book.user.id) %></td>
            <td style="border:none;"><%= link_to @book.title,book_path(@book)%></td>
            <td style="border:none;"><%= @book.body %></td>
            
         
          <td class="favorites_buttons_<%= @book.id %>">
        <%= render 'favorites/favorite-btn', book:@book %>
      </td>
                <!-- コメント機能　-->
                  <td>
                      <div class="comment-list bt style-2" id="comments">
                        <div class="float-wrapper">
                          <div class="comment-count">コメント数：<%= @book.book_comments.count %></div>
                        </div>

                  </td>
                   <% if @user.id == current_user.id %>
              <td><span><%= link_to 'Edit', edit_book_path(@book),class: "btn btn-success"  %></span></td>
		          <td><span><%= link_to 'Destroy', book_path(@book), class: "btn btn-danger" ,method: :delete, "data-confirm" => "本当に削除しますか？"  %></span></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div id="comment-create">
        <%= render partial: 'book_comments/comment', locals: { book_comments: @book_comments } %>
      </div>
     <%= form_with(model: [@book,@book_comment], url: book_book_comments_path(@book) ) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :book_comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
    </div>
  </div>
<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>
    </div>
  </div>
</div>

app/views/books/top.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<main>
  <div class="row">
    <div class='top-message col-md-offset-3 col-md-6'>
      <p class ="text.top">
       <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>
       <p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</p>
       <p>you can share and exchange your opinions , inpressions , and emotions</p>
       <p>about various books!</p>
      </p>

    <div class="btn-wrapper">
      <div class="row">
        <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      </div>

      <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
      </div>
    </div>
  </div>
</main>