config/routes.rb
Rails.application.routes.draw do
   devise_for :users
  root 'books#top'
  get 'home/about' => 'books#about'
  get 'search' => 'searches#search'
  resources :users, only: [:index, :edit, :update, :show] do
    resources :relationships, only: [:create, :destroy]
    resources :parents
    get 'relationships/create'
    get 'relationships/destroy'
  end
 
  resources :books, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy] 
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/_error.message.heml.erb
<% if book.errors.any? %>
  <div class="alert alert-warning">
    <div class="erro"><ul>error!
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %></div>
    </ul>
  </div>
<% end %>

app/views/layouts/_error.message.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <div class="erro"><ul>error!
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %></div>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/05ab1b53cd.js" crossorigin="anonymous"></script>
  </head>
  <header>
  <div class="container">  <!-- この行を追加 -->
    <div class="row">      <!-- この行を追加 -->
      <div class="col-xs-12">
        <div class="title">Bookers</div>
          <!-- loginの時のヘッダー -->
          <% if user_signed_in? %>
          <div align="right">
          <%= link_to "　Home　",user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
          <%= link_to '　Users　',users_path, class: "glyphicon glyphicon-user users" %>
          <%= link_to '　Books　', books_path, class: "glyphicon glyphicon-book books"%>
          <%= link_to "　Logout　", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout"%>
        </div>
           <!-- logoutの時のヘッダー -->
          <% else %>
        <div align="right">
          <%= link_to "　Home　", root_path, class: "glyphicon glyphicon-home home"%>
          <%= link_to "　About　", home_about_path, class: "glyphicon glyphicon-link about" %>
          <%= link_to "　sign up　", new_user_registration_path , class: "glyphicon glyphicon-edit sign_up" %>
          <%= link_to "　login　", new_user_session_path , class: "glyphicon glyphicon-log-in sign_in" %>
        </div>
          <% end %>
        </div>
      </div>
    </div>
  </header>
<center>
<% if user_signed_in? %>
  <%= form_with url:search_path, method: :get, local:true do |form|  %>
  <%= text_field_tag (:word) %>
  <%= select_tag 'range' ,options_for_select([['User', '1'], ['Book', '2']]) %>
  <%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
  <%= submit_tag "検索" %>
  <% end %>
<% end %>
</center>
  <%= yield %>
  </body>
</html>